
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 100

DATASET_SETS:
  -
    DATASET: 'mpii'
    ROOT: 'data/mpii/'
    TEST_SET: 'valid_half'
    # TEST_SET: 'valid'
    TRAIN_SET: 'train'
  -
    DATASET: 'mpii'
    ROOT: 'data/mpii/'
    TEST_SET: 'valid_half'
    # TEST_SET: 'valid'
    TRAIN_SET: 'train'
  -
    DATASET: 'mpii'
    ROOT: 'data/mpii/'
    TEST_SET: 'valid_half'
    # TEST_SET: 'valid'
    TRAIN_SET: 'train'

DATASET_PROXY:
  DATASET: 'mpii_split_proxy'
  ROOT: 'data/mpii_split_proxy/'
  TEST_SET: 'valid_half'
  # TEST_SET: 'valid'
  TRAIN_SET: 'train_proxy'


DATASET:
  DATASET: 'mpii'
  ROOT: 'data/mpii/'
  # ROOT: 'data/mpii_split_0/' # for evaluate
  # TEST_SET: 'valid'
  TEST_SET: 'valid_half'
  TRAIN_SET: 'train'
  # TRAIN_SET: 'train_split_0' #TODO: 주석요망!!!
  # TRAIN_SET: 'train2017_split'
  FLIP: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  # NUM_JOINTS_HALF_BODY: 8
  # PROB_HALF_BODY: 0.3
  TARGET_KEYPOINT: True
  TARGET_HEATMAP: True
  # CUTMIX: True
  # CUTOUT: False
  AUGMENTATION: ""
  SAME_POS: True
  CLEAN_HIGH: True
  NUMBER_OF_SPLITS: 1

FED:
  FEDAVG: False
  FEDPROX: True
  MU: 1.0
  # MU: 0.1
  PROXY_CLIENT: False

KD_USE: True
KD_ALPHA: 0.1

MODEL:
  INIT_WEIGHTS: true
  NAME: vit
  TYPE: 'small'

  # NUM_JOINTS: 17
  NUM_JOINTS: 16
  # PRETRAINED: 'checkpoints/vitpose_large.pth'
  PRETRAINED: 'checkpoints/mae_pretrain_vit_small.pth'
  
  # Multi-Resolution을 위한 셋팅
  IMAGE_SIZE:
  - 192
  - 256
  HEATMAP_SIZE:
  - 48
  - 64

  # FREEZE_NAME:
  # - "backbone"
  # - "keypoint_head"
  SCALE: 1
  USE_AFTER_KP_HEAD: false 
  SUM_TO_ONE: true
  USE_EXP_KP: False

  USE_GPE: true
  USE_LPE: true
  # USE_GAP: true

  # KD_TARGET: "cls"
  KD_TARGET: "logit_hm"

LOSS:
  HM_LOSS: "JointMSEloss"
  # HM_LOSS: "CEloss"
  # UNC_LOSS: "SoftPlusloss"
  # KD_LOSS: "DistillationLoss"
  # KD_LOSS: "JointMSEloss"

  USE_TARGET_WEIGHT: true
  UNCERTAINTY: false
  NORMALIZED_MAP: false  
  USE_INDEXING: true
  
  HM_LOSS_WEIGHT: 1
  KP_LOSS_WEIGHT: 0.0001
  KD_LOSS_WEIGHT: 1
  
  KD_TAU: 1.0
  KD_TYPE: "smooth-l1" # soft, cosine, l2, None

TRAIN:
  BATCH_SIZE: 32
  SHUFFLE: true
  BEGIN_EPOCH: 0
  # BEGIN_EPOCH: 150
  END_EPOCH: 211
  RESUME: false
  # RESUME: True

  OPTIMIZER: 'adamW'
  LR: 0.00025
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200
  WD: 0.01
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false

  # USE_PROXY: True
  USE_PROXY: false

TEST:
  BATCH_SIZE: 64
  COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  FLIP_TEST: true
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: False
  USE_UDP : True 
  MODULATE_KERNEL: 11
  SHIFT_TEST: False
  SHIFT_HEATMAP: False


EVALUATION:
  INTERVAL: 10
  METRIC: 'mAP'
  SAVE_BEST: 'AP'

# DEBUG:
#   SAVE_BATCH_IMAGES_GT: True
#   SAVE_BATCH_IMAGES_PRED: True
#   SAVE_HEATMAPS_GT: True
#   SAVE_HEATMAPS_PRED: True
